### ISSUE TITLE
Example for Traefik

### ISSUE THREAD

**Issue by bvanwiggen** [NHAS/wag#59]
Hi,

Can you provide an example on how to run the VPN via Traefik? Goal is to make the 2FA portal and Management UI available via SSL:

I've added the following labels:
```
    labels:
      traefik.enable: "1"
      traefik.http.routers.wireguard-token.rule: "Host(`vpn.<URL>.com`) && Path(`/token`)"
      traefik.http.routers.wireguard-token.service: wireguard-token
      traefik.http.services.wireguard-token.loadbalancer.server.port: "8081"        

      traefik.http.routers.wireguard-admin.rule: "Host(`vpn.<URL>.com`) && Path(`/admin`)"
      traefik.http.routers.wireguard-admin.service: wireguard-admin      
      traefik.http.services.wireguard-admin.loadbalancer.server.port: "8082"      
```

Relevant pieces of config.json:

```
   "Proxied": true,
    "ExposePorts": [
         "443/tcp"
    ],
    "NAT": true,
    "ManagementUI": {
        "ListenAddress": ":8082",
        "Enabled": true
    },
    "Webserver": {
        "Public": {
            "ListenAddress": ":8081"
        },
        "Tunnel": {
            "Port": "8080"
        }
    },
```
However, I keep getting a Gateway Timeout error from Traefik
